name: Cypress Smoke Tests

on:
  workflow_dispatch:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress smoke tests
        run: npx cypress run --spec "cypress/e2e/smoke/*"
